name: Deploy rigel-hpl Python Package

on: [push]

jobs:

  deploy:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]

    runs-on: ubuntu-latest

    if: github.event_name == 'release' && github.event.action == 'created'

    steps:

      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
            password: ${{ secrets.PYPI_API_TOKEN }}